image: node:10.10.0

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install now
  only:
    - master

production:
  stage: deploy
  script:
    - |
      ./node_modules/.bin/now \
      -e NODE_ENV=production \
      -e MAILGUN_API_KEY=$MAILGUN_API_KEY \
      -e MAILGUN_DOMAIN=$MAILGUN_DOMAIN \
      -e EMAIL_TO=$EMAIL_TO \
      --token=$NOW_TOKEN --target=production
  environment:
    name: production
    url: https://www.divorcenegotiations.com
  only:
    - master
